name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Install dependencies
        run: pnpm install

      - name: Build for Windows
        run: npm run build:win

      - name: Package files
        run: |
          zip -r release.zip server.exe public

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.zip
